import { test } from "bun:test";
import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { briefToText, parseBrief, readEvidenceContext, verifyEvidenceAnchors } from "../src/brief.ts";
import type { BriefCandidate, CandidateTrap } from "../src/brief.ts";

const FIXTURE: readonly BriefCandidate[] = [
	{
		id: "conc-1",
		title: "Any write to the shared sessions map must hold the ingest lock",
		evidence: "src/ingest/loop.ts:41-58",
		status: "keep",
		rationale: "the ingest hot loop mutates shared state behind a lock callers easily forget.",
	},
	{
		id: "err-1",
		title: "Never swallow or soften auth errors in session refresh paths",
		evidence: "src/auth/session.ts:88",
		status: "drop",
		rationale: "",
	},
	{
		id: "data-1",
		title: "Any migration must update db/schema.sql in the same change",
		evidence: "db/migrations/0042_add_flags.sql",
		status: "keep",
		rationale: "schema and migrations drift apart silently otherwise.",
	},
];

test("round-trip: briefToText → parseBrief reproduces candidates", () => {
	const parsed = parseBrief(briefToText(FIXTURE));
	assert.deepEqual(parsed, { candidates: FIXTURE, skipped: 0 });
});

test("reload preserves a flipped status", () => {
	const first = parseBrief(briefToText(FIXTURE));
	const flipped = first.candidates.map((c) =>
		c.id === "conc-1" ? { ...c, status: "drop" as const } : c,
	);
	const second = parseBrief(briefToText(flipped));
	assert.equal(second.skipped, 0);
	assert.equal(second.candidates.find((c) => c.id === "conc-1")?.status, "drop");
	assert.equal(second.candidates.find((c) => c.id === "err-1")?.status, "drop");
	assert.equal(second.candidates.find((c) => c.id === "data-1")?.status, "keep");
});

test("block missing Evidence is skipped, valid siblings kept", () => {
	const text = [
		"# Advisor brief",
		"",
		"<!-- generated by omp-make-advisor; edit statuses inline (keep|drop) -->",
		"",
		"## conc-1 · keep — Any write to the shared sessions map must hold the ingest lock",
		"Rationale: evidence line absent, so this block is malformed.",
		"",
		"## err-1 · keep — Never swallow or soften auth errors in session refresh paths",
		"Evidence: src/auth/session.ts:88",
		"",
	].join("\n");
	const parsed = parseBrief(text);
	assert.equal(parsed.skipped, 1);
	assert.deepEqual(parsed.candidates.map((c) => c.id), ["err-1"]);
});

test("duplicate id: first block wins, later block skipped", () => {
	const text = [
		"## conc-1 · keep — first title",
		"Evidence: src/a.ts:1",
		"",
		"## conc-1 · drop — second title",
		"Evidence: src/b.ts:2",
	].join("\n");
	const parsed = parseBrief(text);
	assert.equal(parsed.skipped, 1);
	assert.deepEqual(parsed.candidates, [
		{ id: "conc-1", title: "first title", evidence: "src/a.ts:1", status: "keep", rationale: "" },
	]);
});

test("status token normalization", () => {
	const mk = (status: string) => `## x-${status} · ${status} — t\nEvidence: p`;
	const parsed = parseBrief([mk("Pending"), mk("DROP"), mk("garbage")].join("\n\n"));
	assert.equal(parsed.skipped, 0);
	assert.deepEqual(
		parsed.candidates.map((c) => [c.id, c.status]),
		[
			["x-Pending", "keep"],
			["x-DROP", "drop"],
			["x-garbage", "keep"],
		],
	);
});

test("empty and header-only text parse to nothing", () => {
	assert.deepEqual(parseBrief(""), { candidates: [], skipped: 0 });
	assert.deepEqual(parseBrief("# Advisor brief\n\n<!-- comment -->\n"), { candidates: [], skipped: 0 });
});

const ANCHOR_CASES: readonly CandidateTrap[] = [
	{ id: "ok-range", title: "t", evidence: "ingest.ts:1-3" },
	{ id: "ok-bare", title: "t", evidence: "ingest.ts" },
	{ id: "ok-dir", title: "t", evidence: "db" },
	{ id: "ghost", title: "t", evidence: "src/ghost.ts:10" },
	{ id: "past-eof", title: "t", evidence: "ingest.ts:2-9" },
	{ id: "dir-range", title: "t", evidence: "db:1-2" },
];

test("verifyEvidenceAnchors: exact-EOF ranges and bare paths pass; ghost, past-EOF, and ranged dirs fail", () => {
	const dir = mkdtempSync(join(tmpdir(), "oma-anchors-"));
	try {
		writeFileSync(join(dir, "ingest.ts"), "line1\nline2\nline3"); // 3 lines
		mkdirSync(join(dir, "db"));
		assert.deepEqual(verifyEvidenceAnchors(dir, ANCHOR_CASES), [
			{ id: "ghost", evidence: "src/ghost.ts:10", reason: "unresolved" },
			{ id: "past-eof", evidence: "ingest.ts:2-9", reason: "out-of-range" },
			{ id: "dir-range", evidence: "db:1-2", reason: "unresolved" },
		]);
	} finally {
		rmSync(dir, { recursive: true, force: true });
	}
});

test("readEvidenceContext: ranges, caps, bare files, and non-file evidence", () => {
	const dir = mkdtempSync(join(tmpdir(), "oma-evidence-"));
	try {
		const lines = Array.from({ length: 20 }, (_, i) => `l${i + 1}`);
		writeFileSync(join(dir, "src.ts"), `${lines.join("\n")}\n`);
		mkdirSync(join(dir, "db"));
		// Range inside the cap.
		assert.deepEqual(readEvidenceContext(dir, "src.ts:3-5"), {
			startLine: 3,
			lines: ["l3", "l4", "l5"],
			more: 0,
		});
		// Range wider than the cap elides the tail.
		assert.deepEqual(readEvidenceContext(dir, "src.ts:2-12"), {
			startLine: 2,
			lines: ["l2", "l3", "l4", "l5", "l6"],
			more: 6,
		});
		// Single-line anchor.
		assert.deepEqual(readEvidenceContext(dir, "src.ts:4"), { startLine: 4, lines: ["l4"], more: 0 });
		// Exact-EOF range (trailing newline must not count as a line).
		assert.deepEqual(readEvidenceContext(dir, "src.ts:18-20"), {
			startLine: 18,
			lines: ["l18", "l19", "l20"],
			more: 0,
		});
		// Bare file path previews from the top.
		assert.deepEqual(readEvidenceContext(dir, "src.ts"), {
			startLine: 1,
			lines: ["l1", "l2", "l3", "l4", "l5"],
			more: 15,
		});
		// Directory (area guard), missing path, and past-EOF start: no context.
		assert.equal(readEvidenceContext(dir, "db"), null);
		assert.equal(readEvidenceContext(dir, "ghost.ts:1"), null);
		assert.equal(readEvidenceContext(dir, "src.ts:99"), null);
	} finally {
		rmSync(dir, { recursive: true, force: true });
	}
});
