import { test } from "bun:test";
import assert from "node:assert/strict";
import { briefToText, parseBrief } from "../src/brief.ts";
import type { BriefCandidate } from "../src/brief.ts";

const FIXTURE: readonly BriefCandidate[] = [
	{
		id: "conc-1",
		title: "Any write to the shared sessions map must hold the ingest lock",
		evidence: "src/ingest/loop.ts:41-58",
		status: "keep",
		rationale: "the ingest hot loop mutates shared state behind a lock callers easily forget.",
	},
	{
		id: "err-1",
		title: "Never swallow or soften auth errors in session refresh paths",
		evidence: "src/auth/session.ts:88",
		status: "drop",
		rationale: "",
	},
	{
		id: "data-1",
		title: "Any migration must update db/schema.sql in the same change",
		evidence: "db/migrations/0042_add_flags.sql",
		status: "keep",
		rationale: "schema and migrations drift apart silently otherwise.",
	},
];

test("round-trip: briefToText → parseBrief reproduces candidates", () => {
	const parsed = parseBrief(briefToText(FIXTURE));
	assert.deepEqual(parsed, { candidates: FIXTURE, skipped: 0 });
});

test("reload preserves a flipped status", () => {
	const first = parseBrief(briefToText(FIXTURE));
	const flipped = first.candidates.map((c) =>
		c.id === "conc-1" ? { ...c, status: "drop" as const } : c,
	);
	const second = parseBrief(briefToText(flipped));
	assert.equal(second.skipped, 0);
	assert.equal(second.candidates.find((c) => c.id === "conc-1")?.status, "drop");
	assert.equal(second.candidates.find((c) => c.id === "err-1")?.status, "drop");
	assert.equal(second.candidates.find((c) => c.id === "data-1")?.status, "keep");
});

test("block missing Evidence is skipped, valid siblings kept", () => {
	const text = [
		"# Advisor brief",
		"",
		"<!-- generated by omp-make-advisor; edit statuses inline (keep|drop) -->",
		"",
		"## conc-1 · keep — Any write to the shared sessions map must hold the ingest lock",
		"Rationale: evidence line absent, so this block is malformed.",
		"",
		"## err-1 · keep — Never swallow or soften auth errors in session refresh paths",
		"Evidence: src/auth/session.ts:88",
		"",
	].join("\n");
	const parsed = parseBrief(text);
	assert.equal(parsed.skipped, 1);
	assert.deepEqual(parsed.candidates.map((c) => c.id), ["err-1"]);
});

test("duplicate id: first block wins, later block skipped", () => {
	const text = [
		"## conc-1 · keep — first title",
		"Evidence: src/a.ts:1",
		"",
		"## conc-1 · drop — second title",
		"Evidence: src/b.ts:2",
	].join("\n");
	const parsed = parseBrief(text);
	assert.equal(parsed.skipped, 1);
	assert.deepEqual(parsed.candidates, [
		{ id: "conc-1", title: "first title", evidence: "src/a.ts:1", status: "keep", rationale: "" },
	]);
});

test("status token normalization", () => {
	const mk = (status: string) => `## x-${status} · ${status} — t\nEvidence: p`;
	const parsed = parseBrief([mk("Pending"), mk("DROP"), mk("garbage")].join("\n\n"));
	assert.equal(parsed.skipped, 0);
	assert.deepEqual(
		parsed.candidates.map((c) => [c.id, c.status]),
		[
			["x-Pending", "keep"],
			["x-DROP", "drop"],
			["x-garbage", "keep"],
		],
	);
});

test("empty and header-only text parse to nothing", () => {
	assert.deepEqual(parseBrief(""), { candidates: [], skipped: 0 });
	assert.deepEqual(parseBrief("# Advisor brief\n\n<!-- comment -->\n"), { candidates: [], skipped: 0 });
});
