import { test } from "bun:test";
import assert from "node:assert/strict";
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
	loadWatchdogConfigFile,
	serializeWatchdogConfig,
	type WatchdogConfigDoc,
} from "@oh-my-pi/pi-coding-agent/advisor/config";
import { serializeAdvisorConfig } from "../src/advisor-yaml.js";
import { briefToText, parseBrief, type BriefCandidate } from "../src/brief.js";
import {
	besideTarget,
	buildRosterDoc,
	buildWatchdogMd,
	buildWatchdogYml,
	emitBeside,
	WATCHDOG_FILENAME,
	WATCHDOG_SIDECAR_FILENAME,
	WATCHDOG_YML_FILENAME,
	WATCHDOG_YML_SIDECAR_FILENAME,
} from "../src/emit.js";

const FIXTURE: readonly BriefCandidate[] = [
	{
		id: "t1",
		title: "Any write to the shared ingest map must hold the ingest lock",
		evidence: "src/ingest/loop.ts:41-58",
		status: "keep",
		rationale: "Unsynchronized mutation corrupts ingest batches",
	},
	{ id: "t2", title: "Never swallow auth errors in session refresh", evidence: "src/auth/session.ts:88", status: "keep", rationale: "" },
	{ id: "t3", title: "Migration must update db/schema.sql in the same change", evidence: "db/migrations/0042_add_flags.sql", status: "drop", rationale: "Dropped after review" },
];

// Lens-prefixed ids drive the roster derivation (one advisor per present
// lens); the dropped data-1 must not produce a Data Drift Watcher.
const YML_FIXTURE: readonly BriefCandidate[] = [
	{
		id: "conc-1",
		title: "Any write to the shared ingest map must hold the ingest lock",
		evidence: "src/ingest/loop.ts:41-58",
		status: "keep",
		rationale: "Unsynchronized mutation corrupts ingest batches",
	},
	{ id: "err-1", title: "Never swallow auth errors in session refresh", evidence: "src/auth/session.ts:88", status: "keep", rationale: "" },
	{ id: "data-1", title: "Migration must update db/schema.sql in the same change", evidence: "db/migrations/0042_add_flags.sql", status: "drop", rationale: "Dropped after review" },
];

test("buildWatchdogMd golden (kept only, empty rationale form)", () => {
	const expected =
		"# Watchdog notes\n" +
		"\n" +
		"<!-- generated by omp-make-advisor from advisor-brief.md — review, edit, or delete -->\n" +
		"\n" +
		"Especially watch for:\n" +
		"\n" +
		"- **Any write to the shared ingest map must hold the ingest lock** (src/ingest/loop.ts:41-58) — Unsynchronized mutation corrupts ingest batches\n" +
		"- **Never swallow auth errors in session refresh** (src/auth/session.ts:88)\n";
	assert.equal(buildWatchdogMd(FIXTURE), expected);
});

test("buildWatchdogMd round-trip: regeneration from re-parsed briefs is byte-identical", () => {
	const parsed = parseBrief(briefToText(FIXTURE));
	const once = buildWatchdogMd(parsed.candidates);
	// Independent second regeneration: serialize the parsed brief, re-parse,
	// build — the full md→brief→md cycle must be stable.
	const twice = buildWatchdogMd(parseBrief(briefToText(parsed.candidates)).candidates);
	assert.equal(once, twice);
	assert.ok(once.includes("Especially watch for:"), "round-trip output must stay non-trivial");
});

test("buildWatchdogYml golden (lens roster, OMP serializer semantics)", () => {
	const expected =
		"instructions: Starter advisor roster generated by omp-make-advisor from advisor-brief.md; review and tune with /advisor configure.\n" +
		"advisors:\n" +
		"  - name: Concurrency Watcher\n" +
		'    model: "@slow"\n' +
		"    tools:\n" +
		"      - read\n" +
		"      - grep\n" +
		"      - glob\n" +
		"    instructions: |2-\n" +
		"      Watch for unsynchronized writes to shared state, check-then-act sequences, and invariants a refactor could silently break.\n" +
		"      Escalate via advise with the evidence paths recorded in WATCHDOG.md.\n" +
		"  - name: Error Handling Watcher\n" +
		'    model: "@slow"\n' +
		"    tools:\n" +
		"      - read\n" +
		"      - grep\n" +
		"      - glob\n" +
		"    instructions: |2-\n" +
		"      Watch for swallowed, dropped, or silently softened failures, and cleanup or rollback a new early-return would skip.\n" +
		"      Escalate via advise with the evidence paths recorded in WATCHDOG.md.\n";
	assert.equal(buildWatchdogYml(YML_FIXTURE), expected);
});

test("buildWatchdogYml round-trip: loadWatchdogConfigFile → serializeWatchdogConfig is byte-identical", async () => {
	const emitted = buildWatchdogYml(YML_FIXTURE);
	const dir = mkdtempSync(join(tmpdir(), "oma-yml-"));
	try {
		const file = join(dir, WATCHDOG_YML_FILENAME);
		writeFileSync(file, emitted, "utf8");
		const doc = await loadWatchdogConfigFile(file);
		assert.equal(serializeWatchdogConfig(doc), emitted);
	} finally {
		rmSync(dir, { recursive: true, force: true });
	}
});

test("vendored serializer matches OMP's serializeWatchdogConfig on chomp/tool/enabled edges", () => {
	const cases: WatchdogConfigDoc[] = [
		buildRosterDoc(YML_FIXTURE),
		{ instructions: "shared baseline\n", advisors: [{ name: "A", instructions: "one\nline" }] },
		{ instructions: "shared\nbaseline\n\n", advisors: [] },
		{ advisors: [{ name: "A", model: "x/y", tools: [], instructions: "no tools" }] },
		{ advisors: [{ name: "A", tools: ["read"], enabled: false }] },
		{ advisors: [] },
		{ advisors: [{ name: "Quote: @weird", model: "@slow", instructions: "line1\nline2" }] },
	];
	for (const doc of cases) {
		assert.deepEqual(serializeAdvisorConfig(doc), serializeWatchdogConfig(doc), JSON.stringify(doc));
	}
});

test("emitBeside clobber matrix (md and yml pairs)", () => {
	for (const [canonical, sidecar] of [
		[WATCHDOG_FILENAME, WATCHDOG_SIDECAR_FILENAME],
		[WATCHDOG_YML_FILENAME, WATCHDOG_YML_SIDECAR_FILENAME],
	] as const) {
		const dirA = mkdtempSync(join(tmpdir(), "oma-emit-"));
		try {
			assert.equal(besideTarget(dirA, canonical, sidecar), canonical);
			const result = emitBeside(dirA, canonical, sidecar, "content-a\n");
			assert.equal(result.besideStanding, false);
			assert.equal(result.path, join(dirA, canonical));
			assert.equal(readFileSync(join(dirA, canonical), "utf8"), "content-a\n");
			assert.equal(existsSync(join(dirA, sidecar)), false);
		} finally {
			rmSync(dirA, { recursive: true, force: true });
		}

		const dirB = mkdtempSync(join(tmpdir(), "oma-emit-"));
		try {
			const standing = join(dirB, canonical);
			writeFileSync(standing, "standing bytes\n", "utf8");
			const before = readFileSync(standing);
			assert.equal(besideTarget(dirB, canonical, sidecar), sidecar);
			const result = emitBeside(dirB, canonical, sidecar, "content-b\n");
			assert.equal(result.besideStanding, true);
			assert.equal(result.path, join(dirB, sidecar));
			assert.equal(readFileSync(join(dirB, sidecar), "utf8"), "content-b\n");
			assert.deepEqual(readFileSync(standing), before, `standing ${canonical} must be byte-identical`);
		} finally {
			rmSync(dirB, { recursive: true, force: true });
		}
	}
});
