import { test } from "bun:test";
import assert from "node:assert/strict";
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { briefToText, parseBrief, type BriefCandidate } from "../src/brief.js";
import { buildWatchdogMd, emitWatchdog, WATCHDOG_FILENAME, WATCHDOG_SIDECAR_FILENAME } from "../src/emit.js";

const FIXTURE: readonly BriefCandidate[] = [
	{
		id: "t1",
		title: "Any write to the shared ingest map must hold the ingest lock",
		evidence: "src/ingest/loop.ts:41-58",
		status: "keep",
		rationale: "Unsynchronized mutation corrupts ingest batches",
	},
	{ id: "t2", title: "Never swallow auth errors in session refresh", evidence: "src/auth/session.ts:88", status: "keep", rationale: "" },
	{ id: "t3", title: "Migration must update db/schema.sql in the same change", evidence: "db/migrations/0042_add_flags.sql", status: "drop", rationale: "Dropped after review" },
];

test("buildWatchdogMd golden (kept only, empty rationale form)", () => {
	const expected =
		"# Watchdog notes\n" +
		"\n" +
		"<!-- generated by omp-make-advisor from advisor-brief.md — review, edit, or delete -->\n" +
		"\n" +
		"Especially watch for:\n" +
		"\n" +
		"- **Any write to the shared ingest map must hold the ingest lock** (src/ingest/loop.ts:41-58) — Unsynchronized mutation corrupts ingest batches\n" +
		"- **Never swallow auth errors in session refresh** (src/auth/session.ts:88)\n";
	assert.equal(buildWatchdogMd(FIXTURE), expected);
});

test("buildWatchdogMd round-trip: regeneration from re-parsed briefs is byte-identical", () => {
	const parsed = parseBrief(briefToText(FIXTURE));
	const once = buildWatchdogMd(parsed.candidates);
	// Independent second regeneration: serialize the parsed brief, re-parse,
	// build — the full md→brief→md cycle must be stable.
	const twice = buildWatchdogMd(parseBrief(briefToText(parsed.candidates)).candidates);
	assert.equal(once, twice);
	assert.ok(once.includes("Especially watch for:"), "round-trip output must stay non-trivial");
});

test("emitWatchdog clobber matrix", () => {
	const dirA = mkdtempSync(join(tmpdir(), "oma-emit-"));
	try {
		const result = emitWatchdog(dirA, "content-a\n");
		assert.equal(result.besideStanding, false);
		assert.equal(result.path, join(dirA, WATCHDOG_FILENAME));
		assert.equal(readFileSync(join(dirA, WATCHDOG_FILENAME), "utf8"), "content-a\n");
		assert.equal(existsSync(join(dirA, WATCHDOG_SIDECAR_FILENAME)), false);
	} finally {
		rmSync(dirA, { recursive: true, force: true });
	}

	const dirB = mkdtempSync(join(tmpdir(), "oma-emit-"));
	try {
		const standing = join(dirB, WATCHDOG_FILENAME);
		writeFileSync(standing, "standing bytes\n", "utf8");
		const before = readFileSync(standing);
		const result = emitWatchdog(dirB, "content-b\n");
		assert.equal(result.besideStanding, true);
		assert.equal(result.path, join(dirB, WATCHDOG_SIDECAR_FILENAME));
		assert.equal(readFileSync(join(dirB, WATCHDOG_SIDECAR_FILENAME), "utf8"), "content-b\n");
		assert.deepEqual(readFileSync(standing), before, "standing WATCHDOG.md must be byte-identical");
	} finally {
		rmSync(dirB, { recursive: true, force: true });
	}
});
