import { WatchdogPreview } from "../../src/preview.js";
import { runOverlayHost } from "./hostlib.js";

const eventsPath = process.argv[2];
if (!eventsPath) throw new Error("usage: bun run test/tui/preview-host.ts <events.jsonl>");

// ~14-line sample WATCHDOG.md body: long bullets exercise 60-col wrapping,
// the tab-indented line exercises replaceTabs, and the final bullet is the
// scroll-flow marker (only visible after the viewport scrolls).
const SAMPLE = [
	"# Watchdog notes",
	"",
	"<!-- generated by omp-make-advisor from advisor-brief.md — review, edit, or delete -->",
	"",
	"Especially watch for:",
	"",
	"- **Any write to the shared ingest map must hold the ingest lock before mutating entries** (src/ingest/loop.ts:41-58) — unsynchronized mutation corrupts ingest batches mid-run",
	"- **Never swallow or soften auth errors in session refresh paths** (src/auth/session.ts:88)",
	"- **Any migration must update db/schema.sql in the same change or reviewers chase phantom columns** (db/migrations/0042_add_flags.sql)",
	"- **Run the unit gate from test/unit/, not test/*.test.ts** (run.sh)",
	"\tIndented note with a tab: gate scripts skip nested suites silently.",
	"- **Pin the ingest worker count in config before scaling horizontally** (src/ingest/worker.ts:12-30)",
].join("\n");

runOverlayHost<boolean>((keybindings, done) => new WatchdogPreview(SAMPLE, "WATCHDOG.md", keybindings, done), eventsPath);
