import { readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export interface CandidateTrap {
	id: string;
	title: string;
	evidence: string; // "" = none (user-authored custom considerations)
}

export interface BriefCandidate extends CandidateTrap {
	status: "keep" | "drop";
	rationale: string; // may be ""
}

export interface BriefParseResult {
	candidates: BriefCandidate[];
	skipped: number; // malformed blocks + duplicate ids
}

export const BRIEF_FILENAME = "advisor-brief.md";

const HEADER = "# Advisor brief";
const COMMENT = "<!-- generated by omp-make-advisor; edit statuses inline (keep|drop) -->";

// Block header: `## <id> · <status> — <title>`. Ids carry no whitespace; the title
// is the rest of the line. Must stay in lockstep with src/scan.ts's prompt.
const BLOCK_START = /^## (\S+) · (\S+) — (.+)$/;
const EVIDENCE_LINE = /^Evidence: (.+)$/;
const RATIONALE_LINE = /^Rationale: (.+)$/;
// Evidence anchors: `path`, `path:line`, `path:line-line` (relative to cwd).
const EVIDENCE_RANGE = /^(.+?):(\d+)(?:-(\d+))?$/;

function normalizeStatus(token: string): "keep" | "drop" {
	const lowered = token.toLowerCase();
	return lowered === "drop" ? "drop" : "keep";
}

interface OpenBlock {
	id: string;
	status: "keep" | "drop";
	title: string;
	evidence: string; // "" until an Evidence: line is seen
	rationale: string;
}

export function parseBrief(text: string): BriefParseResult {
	const candidates: BriefCandidate[] = [];
	const seen = new Set<string>();
	let skipped = 0;
	let current: OpenBlock | null = null;

	const flush = (): void => {
		if (!current) return;
		const block = current;
		current = null;
		if (block.title.trim() === "" || seen.has(block.id)) {
			skipped += 1;
			return;
		}
		seen.add(block.id);
		candidates.push({
			id: block.id,
			title: block.title,
			evidence: block.evidence,
			status: block.status,
			rationale: block.rationale,
		});
	};

	for (const line of text.split("\n")) {
		if (line.startsWith("## ")) {
			flush();
			const start = BLOCK_START.exec(line);
			if (start) {
				current = {
					id: start[1],
					status: normalizeStatus(start[2]),
					title: start[3],
					evidence: "",
					rationale: "",
				};
			}
			continue;
		}
		if (!current) continue;
		const evidence = EVIDENCE_LINE.exec(line);
		if (evidence) {
			current.evidence = evidence[1];
			continue;
		}
		const rationale = RATIONALE_LINE.exec(line);
		if (rationale) current.rationale = rationale[1];
	}
	flush();

	return { candidates, skipped };
}

export function briefToText(candidates: readonly BriefCandidate[]): string {
	const head = [HEADER, "", COMMENT, ""].join("\n");
	if (candidates.length === 0) return head;
	const blocks = candidates.map((c) => {
		const lines = [`## ${c.id} · ${c.status} — ${c.title}`];
		if (c.evidence !== "") lines.push(`Evidence: ${c.evidence}`);
		if (c.rationale !== "") lines.push(`Rationale: ${c.rationale}`);
		return lines.join("\n");
	});
	return head + "\n" + blocks.join("\n\n") + "\n";
}

export function readBrief(
	cwd: string,
): { ok: true; result: BriefParseResult } | { ok: false; error: NodeJS.ErrnoException } {
	try {
		const text = readFileSync(join(cwd, BRIEF_FILENAME), "utf8");
		return { ok: true, result: parseBrief(text) };
	} catch (error) {
		return { ok: false, error: error as NodeJS.ErrnoException };
	}
}

export function writeBrief(cwd: string, candidates: readonly BriefCandidate[]): void {
	writeFileSync(join(cwd, BRIEF_FILENAME), briefToText(candidates), "utf8");
}

// Inline evidence preview for the interview stepper: the anchored source
// lines, or null when the evidence names a directory, a missing path, or a
// degenerate range (area guards stay legitimate evidence without inline
// lines). Raw text is returned — guttering, tab handling, and wrapping are
// render-time concerns.
export interface EvidenceContext {
	startLine: number; // 1-based file line of lines[0]
	lines: readonly string[];
	more: number; // anchor lines elided beyond the cap
}

export function readEvidenceContext(
	cwd: string,
	evidence: string,
	maxLines = 5,
): EvidenceContext | null {
	if (evidence === "") return null; // custom considerations carry no anchor
	const ranged = EVIDENCE_RANGE.exec(evidence);
	let content: string;
	try {
		const abs = join(cwd, ranged ? ranged[1] : evidence);
		if (!statSync(abs).isFile()) return null;
		content = readFileSync(abs, "utf8");
	} catch {
		return null;
	}
	// A trailing newline yields a phantom final element; drop it for display.
	const all = content.split("\n");
	if (all.length > 0 && all[all.length - 1] === "") all.pop();
	const start = ranged ? Number(ranged[2]) : 1;
	const end = Math.min(ranged ? (ranged[3] ? Number(ranged[3]) : Number(ranged[2])) : all.length, all.length);
	if (start < 1 || end < start) return null; // degenerate anchor (:0, inverted, start past EOF)
	const from = Math.max(1, start);
	const lines: string[] = [];
	for (let no = from; no <= end && lines.length < maxLines; no += 1) {
		lines.push(all[no - 1] ?? "");
	}
	return { startLine: from, lines, more: end - from + 1 - lines.length };
}

// Settle-time anchor liveness. parseBrief validates grammar only; scouts can
// hallucinate anchors, and the emit is where that stops being cosmetic.
// Evidence forms: `path`, `path:line`, `path:line-line` (relative to cwd).
// Bare paths may name a directory (an area guard); ranges require a readable
// regular file, 1-based ordered bounds, and a line count that covers them —
// counting real lines only (a trailing newline is not a line), the same
// semantics readEvidenceContext renders by.
export interface AnchorFailure {
	id: string;
	evidence: string;
	reason: "unresolved" | "out-of-range";
}

export function verifyEvidenceAnchors(
	cwd: string,
	candidates: readonly CandidateTrap[],
): AnchorFailure[] {
	const failures: AnchorFailure[] = [];
	for (const candidate of candidates) {
		if (candidate.evidence === "") continue; // custom considerations carry no anchor
		const ranged = EVIDENCE_RANGE.exec(candidate.evidence);
		const abs = join(cwd, ranged ? ranged[1] : candidate.evidence);
		let lines = 0;
		try {
			const isFile = statSync(abs).isFile();
			if (ranged && !isFile) throw new Error("not a regular file");
			// Read only when the line count is consumed; a bare path just has to
			// exist (dirs are legitimate area guards).
			if (ranged && isFile) {
				const all = readFileSync(abs, "utf8").split("\n");
				if (all.length > 0 && all[all.length - 1] === "") all.pop();
				lines = all.length;
			}
		} catch {
			failures.push({ id: candidate.id, evidence: candidate.evidence, reason: "unresolved" });
			continue;
		}
		if (ranged) {
			const start = Number(ranged[2]);
			const end = ranged[3] ? Number(ranged[3]) : start;
			if (start < 1 || start > end || end > lines) {
				failures.push({ id: candidate.id, evidence: candidate.evidence, reason: "out-of-range" });
			}
		}
	}
	return failures;
}
