import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export interface CandidateTrap {
	id: string;
	title: string;
	evidence: string;
}

export interface BriefCandidate extends CandidateTrap {
	status: "keep" | "drop";
	rationale: string; // may be ""
}

export interface BriefParseResult {
	candidates: BriefCandidate[];
	skipped: number; // malformed blocks + duplicate ids
}

export const BRIEF_FILENAME = "advisor-brief.md";

const HEADER = "# Advisor brief";
const COMMENT = "<!-- generated by omp-make-advisor; edit statuses inline (keep|drop) -->";

// Block header: `## <id> · <status> — <title>`. Ids carry no whitespace; the title
// is the rest of the line. Must stay in lockstep with src/scan.ts's prompt.
const BLOCK_START = /^## (\S+) · (\S+) — (.+)$/;
const EVIDENCE_LINE = /^Evidence: (.+)$/;
const RATIONALE_LINE = /^Rationale: (.+)$/;

function normalizeStatus(token: string): "keep" | "drop" {
	const lowered = token.toLowerCase();
	return lowered === "drop" ? "drop" : "keep";
}

interface OpenBlock {
	id: string;
	status: "keep" | "drop";
	title: string;
	evidence: string | null;
	rationale: string;
}

export function parseBrief(text: string): BriefParseResult {
	const candidates: BriefCandidate[] = [];
	const seen = new Set<string>();
	let skipped = 0;
	let current: OpenBlock | null = null;

	const flush = (): void => {
		if (!current) return;
		const block = current;
		current = null;
		if (block.evidence === null || block.title.trim() === "" || seen.has(block.id)) {
			skipped += 1;
			return;
		}
		seen.add(block.id);
		candidates.push({
			id: block.id,
			title: block.title,
			evidence: block.evidence,
			status: block.status,
			rationale: block.rationale,
		});
	};

	for (const line of text.split("\n")) {
		if (line.startsWith("## ")) {
			flush();
			const start = BLOCK_START.exec(line);
			if (start) {
				current = {
					id: start[1],
					status: normalizeStatus(start[2]),
					title: start[3],
					evidence: null,
					rationale: "",
				};
			}
			continue;
		}
		if (!current) continue;
		const evidence = EVIDENCE_LINE.exec(line);
		if (evidence) {
			current.evidence = evidence[1];
			continue;
		}
		const rationale = RATIONALE_LINE.exec(line);
		if (rationale) current.rationale = rationale[1];
	}
	flush();

	return { candidates, skipped };
}

export function briefToText(candidates: readonly BriefCandidate[]): string {
	const head = [HEADER, "", COMMENT, ""].join("\n");
	if (candidates.length === 0) return head;
	const blocks = candidates.map((c) => {
		const lines = [`## ${c.id} · ${c.status} — ${c.title}`, `Evidence: ${c.evidence}`];
		if (c.rationale !== "") lines.push(`Rationale: ${c.rationale}`);
		return lines.join("\n");
	});
	return head + "\n" + blocks.join("\n\n") + "\n";
}

export function readBrief(
	cwd: string,
): { ok: true; result: BriefParseResult } | { ok: false; error: NodeJS.ErrnoException } {
	try {
		const text = readFileSync(join(cwd, BRIEF_FILENAME), "utf8");
		return { ok: true, result: parseBrief(text) };
	} catch (error) {
		return { ok: false, error: error as NodeJS.ErrnoException };
	}
}

export function writeBrief(cwd: string, candidates: readonly BriefCandidate[]): void {
	writeFileSync(join(cwd, BRIEF_FILENAME), briefToText(candidates), "utf8");
}
