import { existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { BriefCandidate } from "./brief.js";

export const WATCHDOG_FILENAME = "WATCHDOG.md";
export const WATCHDOG_SIDECAR_FILENAME = "WATCHDOG.oma.md";

export interface EmitResult {
	path: string;
	besideStanding: boolean;
}

// Byte-stable rendering of kept candidates in brief order. parseBrief
// guarantees title/evidence/rationale are single lines, so the template
// needs no escaping layer. All-dropped input renders the header plus an
// empty list (callers guard, the function stays total).
export function buildWatchdogMd(candidates: readonly BriefCandidate[]): string {
	const bullets = candidates
		.filter((c) => c.status === "keep")
		.map((c) => (c.rationale === "" ? `- **${c.title}** (${c.evidence})` : `- **${c.title}** (${c.evidence}) — ${c.rationale}`));
	return [
		"# Watchdog notes",
		"",
		"<!-- generated by omp-make-advisor from advisor-brief.md — review, edit, or delete -->",
		"",
		"Especially watch for:",
		"",
		...bullets,
	].join("\n") + "\n";
}

// Never mutates a standing WATCHDOG.md — writes the sidecar beside it.
// Write failures propagate (surfaced by omp's command error handling).
export function emitWatchdog(cwd: string, content: string): EmitResult {
	const besideStanding = existsSync(join(cwd, WATCHDOG_FILENAME));
	const path = join(cwd, besideStanding ? WATCHDOG_SIDECAR_FILENAME : WATCHDOG_FILENAME);
	writeFileSync(path, content, "utf8");
	return { path, besideStanding };
}
