import { existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { AdvisorConfig, WatchdogConfigDoc } from "@oh-my-pi/pi-coding-agent/advisor/config";
import { serializeAdvisorConfig } from "./advisor-yaml.js";
import type { BriefCandidate } from "./brief.js";

export const WATCHDOG_FILENAME = "WATCHDOG.md";
export const WATCHDOG_SIDECAR_FILENAME = "WATCHDOG.oma.md";
export const WATCHDOG_YML_FILENAME = "WATCHDOG.yml";
export const WATCHDOG_YML_SIDECAR_FILENAME = "WATCHDOG.oma.yml";

export interface EmitResult {
	path: string;
	besideStanding: boolean;
}

// Byte-stable rendering of kept candidates in brief order. parseBrief
// guarantees title/evidence/rationale are single lines, so the template
// needs no escaping layer. All-dropped input renders the header plus an
// empty list (callers guard, the function stays total).
export function buildWatchdogMd(candidates: readonly BriefCandidate[]): string {
	const bullet = (c: BriefCandidate): string => {
		if (c.evidence === "") return c.rationale === "" ? `- **${c.title}**` : `- **${c.title}** — ${c.rationale}`;
		return c.rationale === "" ? `- **${c.title}** (${c.evidence})` : `- **${c.title}** (${c.evidence}) — ${c.rationale}`;
	};
	const bullets = candidates.filter((c) => c.status === "keep").map(bullet);
	return [
		"# Watchdog notes",
		"",
		"<!-- generated by omp-make-advisor from advisor-brief.md — review, edit, or delete -->",
		"",
		"Especially watch for:",
		"",
		...bullets,
	].join("\n") + "\n";
}

// Starter WATCHDOG.yml roster: kept candidates grouped by lens id prefix —
// one advisor per present lens, top 3 by kept count (LENS_ORDER breaks ties;
// the sort is stable). Kept ids with no lens prefix get a single generic
// fallback advisor, so the minimum roster is one advisor and the doc is never
// empty (OMP deletes WATCHDOG.yml when a save serializes to "").
type Lens = "conc" | "err" | "data" | "build";
const LENS_ORDER: readonly Lens[] = ["conc", "err", "data", "build"];
// Derived from LENS_ORDER so the prefix set cannot drift from the ranking set.
const LENS_PREFIX = new RegExp(`^(${LENS_ORDER.join("|")})-`);
const LENS_ESCALATE = "Escalate via advise with the evidence paths recorded in WATCHDOG.md.";
const LENS_ROLES: Record<Lens, { name: string; focus: string }> = {
	conc: { name: "Concurrency Watcher", focus: "Watch for unsynchronized writes to shared state, check-then-act sequences, and invariants a refactor could silently break." },
	err: { name: "Error Handling Watcher", focus: "Watch for swallowed, dropped, or silently softened failures, and cleanup or rollback a new early-return would skip." },
	data: { name: "Data Drift Watcher", focus: "Watch for schema, migration, and fixture drift, and external data shapes consumed without validation." },
	build: { name: "Build Gate Watcher", focus: "Watch for reordered or repointed scripts and flags, stale generated code, and config diverging from the code it drives." },
};
const FALLBACK_ROLE = { name: "Consideration Watcher", focus: "Watch for the project-specific watch-rules recorded in WATCHDOG.md." };

export function buildRosterDoc(candidates: readonly BriefCandidate[]): WatchdogConfigDoc {
	const counts = new Map<Lens, number>();
	for (const c of candidates) {
		if (c.status !== "keep") continue;
		const match = LENS_PREFIX.exec(c.id)?.[1];
		if (match !== undefined) {
			// LENS_PREFIX is derived from LENS_ORDER, so every capture is a Lens.
			const lens = match as Lens;
			counts.set(lens, (counts.get(lens) ?? 0) + 1);
		}
	}
	const lenses = LENS_ORDER.filter((lens) => counts.has(lens))
		.sort((a, b) => (counts.get(b) ?? 0) - (counts.get(a) ?? 0))
		.slice(0, 3);
	const roles = lenses.map((lens) => ({ ...LENS_ROLES[lens], escalate: LENS_ESCALATE }));
	if (roles.length === 0) roles.push({ ...FALLBACK_ROLE, escalate: "Escalate via advise with the evidence paths cited there." });
	const advisors: AdvisorConfig[] = roles.map(({ name, focus, escalate }) => ({
		name,
		// @slow mirrors what model omission resolves to (the advisor role's
		// slow chain) while staying visible and portable; a concrete provider
		// id would strand a no_model advisor on machines without it.
		model: "@slow",
		tools: ["read", "grep", "glob"],
		instructions: `${focus}\n${escalate}`,
	}));
	return {
		instructions: "Starter advisor roster generated by omp-make-advisor from advisor-brief.md; review and tune with /advisor configure.",
		advisors,
	};
}

// Serialization uses the vendored copy of OMP's serializer
// (src/advisor-yaml.ts) — see its header comment for why a runtime import
// of @oh-my-pi/pi-coding-agent/advisor/config is not loadable under omp
// outside this repo. Equivalence with OMP's real serializer is pinned by
// test/emit.test.ts.
export function buildWatchdogYml(candidates: readonly BriefCandidate[]): string {
	return serializeAdvisorConfig(buildRosterDoc(candidates));
}

// The name emitBeside will write — used by the preview headers. The
// completion notify reports emitBeside's result instead (post-write truth).
export function besideTarget(cwd: string, canonicalName: string, sidecarName: string): string {
	return existsSync(join(cwd, canonicalName)) ? sidecarName : canonicalName;
}

// Never mutates a standing canonical file — writes the sidecar beside it.
// Write failures propagate (surfaced by omp's command error handling).
export function emitBeside(cwd: string, canonicalName: string, sidecarName: string, content: string): EmitResult {
	const besideStanding = existsSync(join(cwd, canonicalName));
	const path = join(cwd, besideStanding ? sidecarName : canonicalName);
	writeFileSync(path, content, "utf8");
	return { path, besideStanding };
}
