// The scan-phase prompt sent to the session agent. The candidate-block shape and
// the advisor-brief.md layout below are the load-bearing contract shared with
// src/brief.ts's parser — change them together or not at all.
export const SCOUT_LENSES = ["conc", "err", "data", "build"] as const;

export function buildScanPrompt(): string {
	return `You are running the omp-make-advisor scan phase. Fan out exactly 4 parallel read-only scout
tasks using your task/subagent tool, one per lens:

1. conc — future concurrency hazards: shared state a future change could touch without the
   right lock; check-then-act sequences a new caller could break; invariants a refactor
   could silently violate.
2. err — future error-handling hazards: paths where a future change could swallow, drop, or
   silently soften a failure; cleanup or rollback a new early-return would skip.
3. data — future data-drift hazards: schema/migration/fixture surfaces that can drift apart
   in a later change; external data shapes consumed without validation that one new field
   would break.
4. build — future build/tooling hazards: scripts or flags a future change could reorder,
   repoint, or run under the wrong defaults; generated code that can go stale; config that
   can diverge from the code it drives.

A trap is NOT a report of a bug that exists today. It is a watch-rule for this project's
advisor: a concrete, project-specific statement of what a future change must not do (or must
always do) in a given area, derived from fragile patterns, load-bearing invariants, or past
near-misses visible in the code and history. You may consult git history for recurring
incident patterns, but every candidate must be phrased about the future.

Scout contract (strict):
- Read-only: scouts must not write, mutate, or install anything.
- Each scout returns AT MOST 3 candidates.
- Each candidate is a markdown block exactly in this shape:

## <id> · keep — <title>
Evidence: <path or path:line or path:line-line>
Rationale: <one sentence>

- <id> = lens prefix + number (conc-1, err-2, ...); no spaces.
- <title> is one line phrased as a watch-rule: "Any <change> to <area> must/must not
  <constraint>" (or the equivalent imperative form).
- Evidence is the existing repository path the rule guards — the fragile area itself, not
  proof of a current defect.
- Rationale says why the risk is real: the fragile pattern, the invariant, or the past
  near-miss.
- No prose outside the blocks.

After all scouts return: merge their blocks, drop duplicates and weak rules (strongest
<= 12 total, each block keeping its exact shape), and write the result to advisor-brief.md at
the repository root using exactly this layout:

# Advisor brief

<!-- generated by omp-make-advisor; edit statuses inline (keep|drop) -->

<candidate blocks separated by blank lines>

Then reply with exactly one line: "oma: scan wrote N candidates to advisor-brief.md".`;
}
